version: '3'
services:
  web:
    image: "alangomes/qmobile-api"
    ports:
     - "80:80"
    environment:
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
    restart: always
    healthcheck:
      test: curl -f http://localhost:80/ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - mariadb
      - redis
    volumes:
      - qmobile-data:/opt/app/data
  redis:
    image: "redis:alpine"
    restart: always
  mariadb:
    image: "nimmis/alpine-mariadb"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '12345'
      MARIADB_DATABASE: qmobile
      MARIADB_REMOTE_ROOT: 'yes'
    volumes:
      - qmobile-db:/var/lib/mysql

volumes:
  qmobile-db:
  qmobile-data:
