version: '3'
services:
  web:
    image: "alangomes/qmobile-api"
    ports:
     - "80:80"
    environment:
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
    healthcheck:
      test: curl -f http://localhost:3002 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - mariadb
      - redis
    volumes:
      - qmobile-data:/opt/app/data
  redis:
    image: "redis:alpine"
  mariadb:
    image: "mariadb:10.2.13"
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: qmobile
    healthcheck:
      test: curl -f http://localhost:3306 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
    - qmobile-db:/var/lib/mysql
