version: 2
jobs:
  build:
    docker:
      - image: adimit/docker-node-chromium
      - image: redis:3.2
      - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_USER: postgres
        - POSTGRES_PASSWORD: postgres
        - POSTGRES_DB: qmobile_test
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install --no-progress
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
