version: 2
jobs:
  build:
    docker:
      - image: adimit/docker-node-chromium
      - image: redis:3.2
      - image: mariadb:10.2.13
        environment:
        - MYSQL_ROOT_PASSWORD: 12345
        - MYSQL_DATABASE: qmobile
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1.1-dependencies-{{ checksum "package.json" }}
          - v1.1-dependencies-
      - run: npm install --no-progress
      - save_cache:
          paths:
            - node_modules
          key: v1.1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm run test:ci
